function row = dt3_empty_row()
% DT3_EMPTY_ROW   Phase-3 extended trace schema (superset of twin_empty_row).
% One row per frame per strategy. NaN = explicitly unavailable (never
% fabricated). See PHASE 3 spec section 7.

row = struct( ...
    'timestamp',     string(""), ...
    'scenario',      string(""), ...
    'mode',          string(""), ...
    'strategy',      string(""), ...        % fixed_otfs|fixed_oddm|ai_adaptive|oracle
    'frame',         int64(-1), ...
    't_s',           NaN, ...
    'environment',   string(""), ...
    'speed_kmph',    NaN, ...
    'snr_db',        NaN, ...
    'doppler_hz',    NaN, ...
    'carrier_frequency_hz', NaN, ...
    'bandwidth_hz',  NaN, ...
    'channel_profile', string(""), ...
    'modulation',    NaN, ...
    'seed_frame',    NaN, ...               % fairness evidence (section 21)
    'payload_sum',   NaN, ...               % payload checksum (identical across strategies)
    'chan_checksum', NaN, ...               % channel checksum (identical across strategies)
    'num_paths',     NaN, ...
    'delay_spread_taps', NaN, ...
    'predicted_waveform', string(""), ...
    'confidence',    NaN, ...
    'pred_BER_OTFS', NaN, ...
    'pred_BER_ODDM', NaN, ...
    'pred_TP_OTFS',  NaN, ...
    'pred_TP_ODDM',  NaN, ...
    'pred_CQI_OTFS', NaN, ...
    'pred_CQI_ODDM', NaN, ...
    'pred_ACS_OTFS', NaN, ...
    'pred_ACS_ODDM', NaN, ...
    'unc_ACS_OTFS',  NaN, ...               % phase-4: RF tree-spread (NaN = n/a)
    'unc_ACS_ODDM',  NaN, ...
    'unc_LogBER_OTFS', NaN, ...
    'unc_LogBER_ODDM', NaN, ...
    'confidence_band', string(""), ...      % phase-4: HIGH|MEDIUM|LOW|''
    'waveform',      string(""), ...        % selected / executed waveform
    'detector',      string(""), ...
    'previous_waveform', string(""), ...
    'switched',      false, ...
    'switch_reason', string(""), ...
    'fallback_used', false, ...
    'error_message', string(""), ...
    'BER',           NaN, ...
    'SER',           NaN, ...
    'PER',           NaN, ...
    'Throughput_bps',NaN, ...
    'SpectralEfficiency_bps_per_Hz', NaN, ...
    'CQI',           NaN, ...
    'Latency_ms',    NaN, ...
    'PacketLoss',    NaN, ...
    'RecoveryRate',  NaN, ...
    'ACS',           NaN, ...
    'oracle_waveform', string(""), ...
    'oracle_BER',    NaN, ...
    'oracle_ACS',    NaN, ...
    'actual_BER_OTFS', NaN, ...
    'actual_ACS_OTFS', NaN, ...
    'actual_BER_ODDM', NaN, ...
    'actual_ACS_ODDM', NaN, ...
    'actual_TP_OTFS',  NaN, ...             % phase-4 paired metrics
    'actual_TP_ODDM',  NaN, ...
    'actual_CQI_OTFS', NaN, ...
    'actual_CQI_ODDM', NaN, ...
    'BER_regret',    NaN, ...
    'relative_BER_regret', NaN, ...
    'ACS_regret',    NaN, ...
    'decision_correct', false, ...
    'error_flag',    false);
end
