% =========================================================================
% STRATEGY_COMPARE   THE key experiment (spec sections 15/16/22/41):
%
%   Fixed OTFS  vs  Fixed ODDM  vs  AI-Adaptive
%
% All three strategies run the SAME changing scenario (scenario.json,
% generated by otfs_ai_pipeline/make_scenario.py) under IDENTICAL per-frame
% conditions: one shared channel realization + one shared payload/noise
% seed per frame, so differences come ONLY from the waveform choice.
%
% The AI-adaptive strategy calls the trained Python engine (ai_engine.py)
% every frame; switching is gated by ACS-improvement threshold + min-dwell.
%
% Outputs (Results\DigitalTwin\):
%   strategy_trace.csv    one row per (strategy, frame), twin_empty_row schema
%   strategy_summary.csv  per-strategy averages + switch counts
% =========================================================================
clearvars; clc;
here = fileparts(mfilename('fullpath'));
outdir = fullfile(here,'Results','DigitalTwin');
if ~exist(outdir,'dir'), mkdir(outdir); end

pyexe = 'C:\MY DATA ANALYTICS FILES AND PROJECTS\MAJOR\AI-Adaptive-Transceiver\.venv\Scripts\python.exe';
if exist(pyexe,'file') ~= 2, pyexe = 'python'; end

scen_file = fullfile(outdir,'scenario.json');
if exist(scen_file,'file') ~= 2
    cmd = sprintf('cd /d "%s" && "%s" make_scenario.py 60.0 "%s"', ...
                  fullfile(here,'otfs_ai_pipeline'), pyexe, scen_file);
    if system(cmd) ~= 0, error('could not generate scenario.json'); end
end
scen = jsondecode(fileread(scen_file));
pts = scen.points;
if ~isfield(pts,'frame'), error('malformed scenario.json'); end
nf = numel(pts);
fprintf('=== STRATEGY COMPARISON: %d frames x 3 strategies ===\n', nf);

strategies = {'fixed_otfs','fixed_oddm','ai_adaptive'};
rows = cell(nf*numel(strategies),1);
ri = 0;
cur_wf = "OTFS"; dwell = 999;

for t = 1:nf
    pt = pts(t);
    seed = 500000 + double(pt.frame);

    % ---- shared channel realization for this frame ----------------------
    pcfg = sim_default_config('DelayProfile',pt.delay_profile, ...
        'Speed_kmph',double(pt.speed_kmph),'SNR_dB',double(pt.snr_db), ...
        'DopplerScale',double(pt.doppler_scale), ...
        'Modulation',double(pt.modulation));
    chan = gen_channel_params_flex(pcfg);

    % ---- run BOTH candidates once (paired) -------------------------------
    cbp = sim_default_config(); cbp.chan = chan; cbp.TwinStrategy = 'pair';
    [rowO,resO] = twin_run_frame(pt,cbp,'OTFS','MRC',seed);
    [rowD,resD] = twin_run_frame(pt,cbp,'ODDM','LMMSE',seed);
    actual = struct('OTFS',resO,'ODDM',resD);

    % ---- three strategy rows ----------------------------------------------
    dec = [];
    for s = 1:numel(strategies)
        strat = strategies{s};
        sw = false; reason = '';
        switch strat
            case 'fixed_otfs'
                wf='OTFS'; det='MRC';
            case 'fixed_oddm'
                wf='ODDM'; det='LMMSE';
            otherwise
                [dec,~] = ai_decide_frame(pt,chan,sim_default_config(), ...
                                          cur_wf,dwell,outdir);
                wf = char(dec.recommendation); sw = logical(dec.switched);
                reason = string(dec.reason);
                det = ''; %#ok<NASGU>
        end
        if strcmp(strat,'fixed_otfs')
            row = rowO;
        elseif strcmp(strat,'fixed_oddm')
            row = rowD;
        else
            % reuse the paired result of the chosen candidate -- identical
            % channel/bits/noise make a re-run pointless
            row = rowO; if strcmpi(wf,'ODDM'), row = rowD; end
            row.waveform = string(wf);
            row.switched = sw; row.switch_reason = reason;
            if isstruct(dec) && isfield(dec,'predicted_ACS')
                row.pred_ACS_OTFS = dec.predicted_ACS.OTFS;
                row.pred_ACS_ODDM = dec.predicted_ACS.ODDM;
            end
            if isstruct(dec) && isfield(dec,'predicted_metrics')
                pm = dec.predicted_metrics.(wf);
                row.predicted_BER_chosen = pm.BER;
                row.predicted_TP_chosen  = pm.Throughput_bps;
                row.predicted_CQI_chosen = pm.CQI;
            end
            row.detector = twin_default_detector(wf);
        end
        row.strategy = string(strat);
        row.actual_BER_OTFS = resO.BER;  row.actual_BER_ODDM = resD.BER;
        row.actual_ACS_OTFS = resO.ACS;  row.actual_ACS_ODDM = resD.ACS;
        ri = ri+1; rows{ri} = row;
    end
    if ~isempty(dec) && isstruct(dec) && logical(dec.switched)
        dwell = 0; cur_wf = string(dec.recommendation);
    else
        dwell = dwell + 1;
    end
    fprintf('f%02d %-11s %5.1fkph %4.1fdB | OTFS %.2e/%.2f  ODDM %.2e/%.2f | AI:%s\n', ...
        t, pt.environment, pt.speed_kmph, pt.snr_db, resO.BER, resO.ACS, ...
        resD.BER, resD.ACS, ternary_str(~isempty(dec),char(string(dec.reason))));
end

T = struct2table([rows{:}]);
writetable(T, fullfile(outdir,'strategy_trace.csv'));

% ---- summary ------------------------------------------------------------------
sumrows = [struct('strategy',"", 'mean_BER',NaN,'median_BER',NaN, ...
    'mean_throughput_kbps',NaN,'mean_SE',NaN,'mean_CQI',NaN, ...
    'mean_latency_ms',NaN,'recovery_rate',NaN,'mean_ACS',NaN, ...
    'switches',int64(0),'frames',int64(0))];
for s = 1:numel(strategies)
    sub = T(strcmp(T.strategy,strategies{s}),:);
    sumrows(s).strategy = string(strategies{s});   % Phase 1 fix: label every row
    sumrows(s).mean_BER = mean(sub.BER);
    sumrows(s).median_BER = median(sub.BER);
    sumrows(s).mean_throughput_kbps = mean(sub.Throughput_bps)/1e3;
    sumrows(s).mean_SE = mean(sub.SpectralEfficiency_bps_per_Hz);
    sumrows(s).mean_CQI = mean(sub.CQI);
    sumrows(s).mean_latency_ms = mean(sub.Latency_ms);
    sumrows(s).recovery_rate = mean(sub.RecoveryRate);
    sumrows(s).mean_ACS = mean(sub.ACS);
    sumrows(s).switches = int64(sum(sub.switched));
    sumrows(s).frames = int64(height(sub));
end
S = struct2table(sumrows);
writetable(S, fullfile(outdir,'strategy_summary.csv'));
fprintf('\n%s\n', repmat('=',1,78));
disp(S);
fprintf('%s\nStrategy trace -> %s\n', repmat('=',1,78), ...
        fullfile(outdir,'strategy_trace.csv'));

function out = ternary_str(c,a)
% [PHASE-5 NOTE] LEGACY Phase-2 evaluation harness (different seed scheme, kept for provenance). Canonical runner: run_experiment.m.
if c, out=a; else, out='-'; end
end
