function row = twin_empty_row()
% TWIN_EMPTY_ROW   Canonical row schema for the Digital Twin trace CSVs.
% Every consumer (runtime, strategy compare, dashboard) fills THIS struct
% so column order/names stay identical everywhere. NaN = not applicable.

row = struct( ...
    'strategy',      string(""), ...
    'frame',         int64(-1), ...
    't_s',           NaN, ...
    'environment',   string(""), ...
    'speed_kmph',    NaN, ...
    'snr_db',        NaN, ...
    'doppler_hz',    NaN, ...
    'delay_profile', string(""), ...
    'doppler_scale', NaN, ...
    'num_paths',     NaN, ...
    'delay_spread_taps', NaN, ...
    'modulation',    NaN, ...
    'waveform',      string(""), ...
    'detector',      string(""), ...
    'BER',           NaN, ...
    'SER',           NaN, ...
    'PER',           NaN, ...
    'Throughput_bps',NaN, ...
    'SpectralEfficiency_bps_per_Hz', NaN, ...
    'CQI',           NaN, ...
    'Latency_ms',    NaN, ...
    'PacketLoss',    NaN, ...
    'RecoveryRate',  NaN, ...
    'ACS',           NaN, ...
    'switched',      false, ...
    'switch_reason', string(""), ...
    'pred_ACS_OTFS', NaN, ...
    'pred_ACS_ODDM', NaN, ...
    'predicted_BER_chosen',  NaN, ...
    'predicted_TP_chosen',   NaN, ...
    'predicted_CQI_chosen',  NaN, ...
    'actual_BER_OTFS', NaN, ...
    'actual_BER_ODDM', NaN, ...
    'actual_ACS_OTFS', NaN, ...
    'actual_ACS_ODDM', NaN, ...
    'error_flag',    false);
end
